; ; PlatformIO Project Configuration File
; ;
; ;   Build options: build flags, source filter
; ;   Upload options: custom upload port, speed and extra flags
; ;   Library options: dependencies, extra library storages
; ;   Advanced options: extra scripting
; ;
; ; Please visit documentation for the other options and examples
; ; https://docs.platformio.org/page/projectconf.html

; [env:nodemcu-32s]
; platform = espressif32
; board = nodemcu-32s
; framework = arduino
; monitor_speed = 115200
; ;lib_deps =   adafruit/Adafruit MAX31865 library @ 1.6.2

[platformio]
default_envs = nodemcu-32s

[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino

monitor_speed = 115200
upload_speed = 921600

board_build.partitions = default.csv
board_upload.flash_size = 4MB
board_build.flash_mode = dio

; lib_deps =
;     bblanchon/ArduinoJson@^7.0.0
;     https://github.com/mathieucarbou/ESPAsyncWebServer.git@^3.1.1
;     https://github.com/mathieucarbou/AsyncTCP.git@^3.1.4

lib_ignore =
    AsyncTCP_RP2040W

build_flags =
    -DARDUINO_ARCH_ESP32
    -DCORE_DEBUG_LEVEL=0