[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200

; lib_deps =
;     bblanchon/ArduinoJson@^7.0.0
;     https://github.com/mathieucarbou/ESPAsyncWebServer.git@^3.1.1
;     https://github.com/mathieucarbou/AsyncTCP.git@^3.1.4

lib_ignore =
    ESPAsyncTCP-esphome
    AsyncTCP_RP2040W

build_flags =
    -Wno-deprecated-declarations